"""add fulfilled fields to token_request_items

Revision ID: 975f08dc0b4c
Revises: dota_tokens_001
Create Date: 2026-08-26 02:09:26.445552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '975f08dc0b4c'
down_revision: Union[str, Sequence[str], None] = 'dota_tokens_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token_request_items', sa.Column('fulfilled', sa.Boolean(), nullable=False, server_default='0'))
    op.add_column('token_request_items', sa.Column('fulfilled_by', sa.BigInteger(), nullable=True))
    op.add_column('token_request_items', sa.Column('fulfilled_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('token_request_items', 'fulfilled_at')
    op.drop_column('token_request_items', 'fulfilled_by')
    op.drop_column('token_request_items', 'fulfilled')
    op.create_table('voice_counters',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('month', sa.INTEGER(), nullable=False),
    sa.Column('year', sa.INTEGER(), nullable=False),
    sa.Column('count', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
