"""add steam fields to users

Revision ID: 9eed3551b0f7
Revises: fc10c710071d
Create Date: 2026-08-26 02:37:19.676088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9eed3551b0f7'
down_revision: Union[str, Sequence[str], None] = 'fc10c710071d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('steam_url', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('steam_nickname', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('steam_avatar_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'steam_avatar_url')
    op.drop_column('users', 'steam_nickname')
    op.drop_column('users', 'steam_url')
    # ### end Alembic commands ###
