"""add block fields to users

Revision ID: edc5e49fb5df
Revises: 9eed3551b0f7
Create Date: 2026-08-26 03:01:04.127210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edc5e49fb5df'
down_revision: Union[str, Sequence[str], None] = '9eed3551b0f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('blocked_sending', sa.Boolean(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('blocked_creating', sa.Boolean(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'blocked_creating')
    op.drop_column('users', 'blocked_sending')
    # ### end Alembic commands ###
