"""add creation_bonus to token_requests

Revision ID: efcbe2badede
Revises: 975f08dc0b4c
Create Date: 2026-08-26 02:11:16.727434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efcbe2badede'
down_revision: Union[str, Sequence[str], None] = '975f08dc0b4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token_requests', sa.Column('creation_bonus', sa.Boolean(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('token_requests', 'creation_bonus')
    # ### end Alembic commands ###
