"""add thread_id to token_requests

Revision ID: fc10c710071d
Revises: efcbe2badede
Create Date: 2026-08-26 02:30:44.157270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc10c710071d'
down_revision: Union[str, Sequence[str], None] = 'efcbe2badede'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token_requests', sa.Column('thread_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('token_requests', 'thread_id')
    # ### end Alembic commands ###
